# docker-compose.yml
version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: mruser
      POSTGRES_PASSWORD: mruser
      POSTGRES_DB: mrdb
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
